# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "30c9fe3549da8a346de11d486d817b2d"
application_url = "https://tables-detroit-lessons-planes.trycloudflare.com"
embedded = true
name = "Card Charges"
handle = "card-charges"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://tables-detroit-lessons-planes.trycloudflare.com/auth/callback",
  "https://tables-detroit-lessons-planes.trycloudflare.com/auth/shopify/callback",
  "https://tables-detroit-lessons-planes.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "kick-start-canada.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
